CREATE TABLE `account` (
  `account_id` varchar(50) NOT NULL,
  `password` varchar(100) DEFAULT NULL,
  `secured_question` varchar(50) DEFAULT NULL,
  `secured_answer` varchar(50) DEFAULT NULL,
  `email` varchar(50) DEFAULT NULL,
  `cell_phone` varchar(20) DEFAULT NULL,
  `user_name` varchar(50) DEFAULT NULL,
  `created_time` datetime DEFAULT NULL,
  `updated_time` datetime DEFAULT NULL,
  `repeat_password` varchar(100) DEFAULT NULL,
  `job` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 


CREATE TABLE `medical_history_summary` (
  `user_id` int(11) NOT NULL,
  `diagnose` varchar(100) DEFAULT NULL,
  `proposed_plan` varchar(50) DEFAULT NULL,
  `created_time` date DEFAULT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 


CREATE TABLE `patients_day1` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) DEFAULT NULL,
  `occupation` varchar(100) DEFAULT NULL,
  `academicdegree` varchar(100) DEFAULT NULL,
  `nationality` varchar(100) DEFAULT NULL,
  `certificateid` varchar(100) DEFAULT NULL,
  `address` varchar(100) DEFAULT NULL,
  `chiefcomplaint` varchar(100) DEFAULT NULL,
  `phoneno` varchar(100) DEFAULT NULL,
  `belongstodoctor` varchar(100) DEFAULT NULL,
  `createdtime` varchar(100) DEFAULT NULL,
  `age` varchar(100) DEFAULT NULL,
  `weight` varchar(100) DEFAULT NULL,
  `height` varchar(100) DEFAULT NULL,
  `bmi` varchar(100) DEFAULT NULL,
  `afcright` varchar(100) DEFAULT NULL,
  `afcleft` varchar(100) DEFAULT NULL,
  `bfsh` varchar(100) DEFAULT NULL,
  `amh` varchar(100) DEFAULT NULL,
  `lefttube` varchar(100) DEFAULT NULL,
  `righttube` varchar(100) DEFAULT NULL,
  `pelvic` varchar(100) DEFAULT NULL,
  `uteruslen` varchar(100) DEFAULT NULL,
  `uteruswidth` varchar(100) DEFAULT NULL,
  `uterusheight` varchar(100) DEFAULT NULL,
  `membrane` varchar(100) DEFAULT NULL,
  `level` varchar(100) DEFAULT NULL,
  `folliclesright` varchar(100) DEFAULT NULL,
  `folliclesleft` varchar(100) DEFAULT NULL,
  `rightovary` varchar(100) DEFAULT NULL,
  `rightovary1` varchar(100) DEFAULT NULL,
  `leftovary` varchar(100) DEFAULT NULL,
  `leftovary1` varchar(100) DEFAULT NULL,
  `lmpdate` varchar(100) DEFAULT NULL,
  `ovarydate` varchar(100) DEFAULT NULL,
  `hascoh` varchar(100) DEFAULT NULL,
  `hasovalation` varchar(100) DEFAULT NULL,
  `ovaryresult` varchar(100) DEFAULT NULL,
  `operationdate` varchar(100) DEFAULT NULL,
  `operationway` varchar(100) DEFAULT NULL,
  `oviduct` varchar(100) DEFAULT NULL,
  `uterus` varchar(100) DEFAULT NULL,
  `ovary` varchar(100) DEFAULT NULL,
  `pelvic1` varchar(100) DEFAULT NULL,
  `result` varchar(100) DEFAULT NULL,
  `iuidate` varchar(100) DEFAULT NULL,
  `iuiresult` varchar(100) DEFAULT NULL,
  `iui` varchar(100) DEFAULT NULL,
  `ivfdate` varchar(100) DEFAULT NULL,
  `ivf` varchar(100) DEFAULT NULL,
  `oocyteretrieval` varchar(100) DEFAULT NULL,
  `mo` varchar(100) DEFAULT NULL,
  `fertilization` varchar(100) DEFAULT NULL,
  `embryo` varchar(100) DEFAULT NULL,
  `transferable` varchar(100) DEFAULT NULL,
  `transfer` varchar(100) DEFAULT NULL,
  `transfercount` varchar(100) DEFAULT NULL,
  `transferresult` varchar(100) DEFAULT NULL,
  `hepatitis` varchar(100) DEFAULT NULL,
  `tuberculosis` varchar(100) DEFAULT NULL,
  `kidney` varchar(100) DEFAULT NULL,
  `cardiovascular` varchar(100) DEFAULT NULL,
  `urinary` varchar(100) DEFAULT NULL,
  `venereal` varchar(100) DEFAULT NULL,
  `appendicitis` varchar(100) DEFAULT NULL,
  `httpmessageconverter` varchar(100) DEFAULT NULL,
  `operationhistory` varchar(100) DEFAULT NULL,
  `otherreason` varchar(100) DEFAULT NULL,
  `others` varchar(100) DEFAULT NULL,
  `smoking` varchar(100) DEFAULT NULL,
  `smokecount` varchar(100) DEFAULT NULL,
  `drunk` varchar(100) DEFAULT NULL,
  `drug` varchar(100) DEFAULT NULL,
  `medicines` varchar(100) DEFAULT NULL,
  `medicinedetail` varchar(100) DEFAULT NULL,
  `medicinesallergic` varchar(100) DEFAULT NULL,
  `allergicdesc` varchar(100) DEFAULT NULL,
  `mentalstimulation` varchar(100) DEFAULT NULL,
  `past` varchar(100) DEFAULT NULL,
  `now` varchar(100) DEFAULT NULL,
  `birthdefect` varchar(100) DEFAULT NULL,
  `defectdetail` varchar(100) DEFAULT NULL,
  `proximity` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `patient_medical_history_xref` (
  `user_id` int(11) NOT NULL,
  `medical_record_id` int(11) NOT NULL,
  `medical_record_type` varchar(20) NOT NULL,
  PRIMARY KEY (`user_id`,`medical_record_id`,`medical_record_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8


CREATE TABLE `patient_medical_record_xref` (
  `medical_record_id` varchar(255) NOT NULL,
  `medical_record_type` varchar(255) NOT NULL,
  `patient_id` varchar(255) NOT NULL,
  PRIMARY KEY (`medical_record_id`,`medical_record_type`,`patient_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
